/* Intro.swift --> VisibleSounds. Created by Miguel Torres on 18/04/23. */

import SwiftUI

struct Intro: View {
    
    @State var times: Double = 0.0
    @EnvironmentObject var audioPlayer: AudioPlayer
    
    var body: some View {
            ZStack {
                Image("Back01")
                    .resizable()
                    .ignoresSafeArea(.all)
                    VStack {
                        Text("Cymatics")
                            .font(.largeTitle)
                            .fontWeight(.heavy)
                            .foregroundColor(Color.white)
                            .padding(.top, 30)
                        HStack {
                            Text("Cymatics is the study of something invisible to our eyes: the hidden geometry within the vibrations generated by sound. Ernst Chladni, a German musician and philosopher, discovered these figures by vibrating a metal plate with a violin bow, and named them Chladni patterns.")
                                .font(.title2)
                                .fontWeight(.medium)
                                .multilineTextAlignment(.center)
                                .foregroundColor(Color.white)
                                .padding(50)
                            Image("Violin")
                                .resizable()
                                .aspectRatio(contentMode: .fit)
                                .padding(100)
                        }
                        // We create the navigation link indicating that the observable object "audioPlayer" is passed to the next view.
                        NavigationLink(destination: SecondView().environmentObject(audioPlayer)) {
                            ZStack {
                                Image(systemName: "arrowshape.right.fill")
                                    .resizable()
                                    .scaledToFit()
                                    .foregroundColor(Color.gray)
                                    .frame(width: 100)
                                    .padding(20)
                            }
                        }.simultaneousGesture(TapGesture().onEnded({
                            audioPlayer.playS(resourceName: "Jump", resourceExtension: "mp3")
                        }))
                    }
            }
    }
}

struct SwiftUIView_Previews: PreviewProvider {
    static let audioPlayer = AudioPlayer()
    static var previews: some View {
        Intro()
            .environmentObject(audioPlayer)
    }
}
